### PR TITLE
Add acknowledge_timeout and remove notified and emailed

### PR DESCRIPTION
**Pull request by enjuthulung**
### Summary:

- Added `acknowledge_timeout`.
- Removed `notified` and `emailed`.

### CODE REVIEW

**Comment by CanuckMarc** [comment]
@enjuthulung why are `notified` and `emailed` being removed?  are they not used?

**Comment by RaiBnod** [comment]
@CanuckMarc I asked him to remove these because now we are trying to send emails and notifications by convention instead of these flags. If we use these flags, the convention won't work properly as our expectation.

**Comment by CanuckMarc** [comment]
ok sounds good.  Was just curious

**Review by CanuckMarc — APPROVED** [review]
Model changes are good.

**Review by RaiBnod — APPROVED** [review]

**Pull request merged**
